services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: auth_postgres
    restart: always
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_PASSWORD=albin
      - POSTGRES_USER=albin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data\
volumes:
  postgres_data:
