version: '3.8'

networks:
  nearca-network:
    driver: bridge

services:
  #service discovery configuration
  discovery-service:
    build:
      context: ./discovery-service/discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"

  # gateway service configration
  gateway-service:
    build:
      context: ./gateway-service/gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
  postgres:
    image: postgres:17-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Albinreji@30
    ports:
      - "5432:5432"
    networks:
      - nearca-network
# auth-service configuration
  auth-service:
    build: 
      context: ./auth-service/auth-service
    container_name: auth-service
    depends_on:
      - postgres
    environment:
      JWT_SECRET: your_very_long_and_very_secure_secret_key_here
      JWT_EXPIRATION: 3600000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Albinreji@30
    ports:
      - "8081:8081"
    networks:
      - nearca-network

    