server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    # If running in Docker Compose, replace 'localhost' with your DB service name
    url: jdbc:postgresql://postgres:5432/auth_db
    username: postgres
    password: Albinreji@30
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # No need to specify the dialect in Hibernate 7+
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # Recommended to disable the warning you had earlier